### ISSUE TITLE
Download URLs are not working anymore

### ISSUE THREAD

**Issue by olvlvl** [mootools/website#199]
Hi,

It looks like download URLs are not working anymore:

http://mootools.net/download/get/mootools-core-1.5.1-full-nocompat.js

We actually need to POST parameters in order to obtain a file. This is **very** unfortunate. Any chance you might fix this and provide resources that we can access with GET?

Thanks.

**Comment by SergioCrisostomo** [comment]
Explanation: https://github.com/mootools/website/pull/205#issuecomment-140366629
