### ISSUE TITLE
More Web Builder broken

### ISSUE THREAD

**Issue by thomasaull** [mootools/website#207]
For me the web builder gives me always the whole stuff, regardless which checkboxes I activate – its always the same 379kb-file.

**Comment by SergioCrisostomo** [comment]
@thomasaull it works fine for me. Do you use the "Download custom MooTools More" button in the end of the page (under the checkboxes)?

**Comment by thomasaull** [comment]
Oh damn, thats embarrassing. I'm sorry for the confusion!
