### ISSUE TITLE
MytechEra - Experience The Technology

### ISSUE THREAD

**Issue by mytechera** [mootools/website#215]
Blog contains latest updated apps for Smartphone and PC & complete Installation steps and latest app features. 
(Windows,Android and Ios platform apps) 
It's also have career spot category which provides tips and tricks 
for make your career more brighter.Have a latest gadgets information.
For more Information Click here <a href="http://mytechera.com/">Mytechera</a>

**Comment by SergioCrisostomo** [comment]
What is this? How is this related with the MooTools website?

**Comment by timwienk** [comment]
> What is this?

This is what spam looks like.
