### ISSUE TITLE
Don't create (or remove) repository when failed to check out tag

### ISSUE THREAD

**Issue by timwienk** [mootools/website#221]
Currently, when a repository for a specific version of Core or More is cloned and the tag is checked out, and the tag does not exist, it does error, but the repository still exists (and stays on master). Next time it attempts to build, it doesn't complain and just keeps what it has (the repository on master).

I guess, now we know this, we can prevent it by removing the repository manually, but it'd be better to prevent it from happening programmatically.

See mootools/mootools-core#2762.
##

**Comment by trendebook** [comment]
was trying to work on this page but it not going 
http://www.trendebook.com/gmail-email-login-gmail-sign-in/
