### ISSUE TITLE
Form.Validator.Inline: par.getScroll is not a function

### ISSUE THREAD

**Issue by masted** [mootools/website#228]
Bug report:

1. Go to http://mootools.net/more/builder
2. Build Form.Validator.Inline with "Add Core (only dependencies)" option
3. Instantiate: new Form.Validator.Inline()
4. Get error "par.getScrollSize() is not a function"

**Comment by SergioCrisostomo** [comment]
@masted checked you steps and got no error: https://jsfiddle.net/s8cc6b9j/
Can you provide more information about it? Browser version, other code you are using, etc. Maybe you can post back a jsFiddle reproducing the problem?

Thanks!

**Comment by masted** [comment]
Normal:
https://jsfiddle.net/empupb87/

Error here:
https://jsfiddle.net/waz01k87/

**Comment by SergioCrisostomo** [comment]
@masted thanks for update. I made a fix suggestion for More, since the problem seems to lie there.
You can fix it by adding `Core/Element.Dimensions` file/module: https://jsfiddle.net/waz01k87/1/

**Comment by masted** [comment]
Cool!
