### ISSUE TITLE
Links to cdn on page  http://mootools.net/core is broken

### ISSUE THREAD

**Issue by xiva-wgt** [mootools/website#229]
links generate script https://github.com/mootools/website/blob/master/core/index.js

this links is broken
http://ajax.googleapis.com/ajax/libs/mootools/1.2.6/mootools-nocompat.js
http://ajax.googleapis.com/ajax/libs/mootools/1.2.6/mootools-nocompat-yui-compressed.js
##

**Comment by SergioCrisostomo** [comment]
@xiva-wgt thanks for reporting this. I sent a fix suggestion for it.

cheers
